# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('abreviacao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EstudoOrientado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(choices=[('Se', 'Segunda'), ('Te', 'Terca'), ('Qa', 'Quarta'), ('Qi', 'Quinta'), ('Sx', 'Sexta')], max_length=2)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudosorientados.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=5)),
                ('fim', models.CharField(max_length=5)),
                ('num_periodo', models.IntegerField()),
                ('turno', models.CharField(choices=[('M', 'Manha'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('foto', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('numero_turma', models.IntegerField(max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudosorientados.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='estudoorientado',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudosorientados.Periodo'),
        ),
        migrations.AddField(
            model_name='estudoorientado',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudosorientados.Turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudosorientados.Professor'),
        ),
    ]
