# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudosorientados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudoorientado',
            name='turnoEO',
            field=models.CharField(choices=[('M', 'Manh\xe3'), ('T', 'Tarde'), ('N', 'Noite')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodo',
            name='turno',
            field=models.CharField(choices=[('M', 'Manh\xe3'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1),
        ),
    ]
