# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudosorientados', '0002_auto_20160821_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudoorientado',
            name='turnoEO',
        ),
        migrations.AddField(
            model_name='turma',
            name='turno_estudo_orientado',
            field=models.CharField(choices=[('M', 'Manh\xe3'), ('T', 'Tarde'), ('N', 'Noite')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
