# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudosorientados', '0004_auto_20160821_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(default='pic_folder/default.jpg', upload_to='pic_folder/'),
        ),
    ]
